export type AppIconKey =
  | 'terminal'
  | 'folder'
  | 'dashboard'
  | 'process'
  | 'runtime'
  | 'docker'
  | 'settings'
  | 'logout'
  | 'editor'
  | 'media'
  | 'link'

export type DesktopAppId =
  | 'terminal'
  | 'files'
  | 'dashboard'
  | 'processes'
  | 'runtime-sessions'
  | 'docker'
  | 'docker-create-container'
  | 'docker-create-compose'
  | 'docker-compose-services'
  | 'settings'
  | 'logout'
  | 'editor'
  | 'media-viewer'
