export type AppIconKey =
  | 'terminal'
  | 'folder'
  | 'dashboard'
  | 'runtime'
  | 'opencode'
  | 'iframe-app'
  | 'docker'
  | 'settings'
  | 'logout'
  | 'editor'
  | 'media'
  | 'link'
  | 'process'
  | 'port-forward'
  | 'operation-log'
  | 'realtime-log'
  | 'cron-task'

export type DesktopAppId =
  | 'terminal'
  | 'files'
  | 'dashboard'
  | 'runtime-sessions'
  | 'opencode'
  | 'iframe-app'
  | 'docker'
  | 'docker-create-container'
  | 'docker-output'
  | 'settings'
  | 'logout'
  | 'editor'
  | 'media-viewer'
  | 'processes'
  | 'port-forward'
  | 'operation-logs'
  | 'realtime-logs'
  | 'cron-tasks'
